name: kaggle
channels:
  - conda-forge
dependencies:
  - bleach=6.2.0=pyh29332c3_4
  - brotli-python=1.1.0=py314he8615de_4
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py314hb14574c_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - kaggle=1.7.4.5=pyhe01879c_0
  - libabseil=20250814.1=cxx17_ha86d76d_0
  - libblas=3.9.0=37_h51639a9_openblas
  - libcblas=3.9.0=37_hb0561ab_openblas
  - libcxx=21.1.3=hf598326_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - liblapack=3.9.0=37_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libmpdec=4.0.0=h5505292_0
  - libopenblas=0.3.30=openmp_h60d53f8_2
  - libsqlite=3.50.4=h4237e3c_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.3=h4a912ad_0
  - ncurses=6.5=h5e97a16_3
  - numpy=2.3.3=py314ha5abc89_0
  - openssl=3.5.4=h5503f6c_0
  - pandas=2.3.3=py314ha3d490a_1
  - pip=25.2=pyh145f28c_0
  - protobuf=6.32.1=py314h0e5b3b2_2
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.14.0=h8929636_101_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-slugify=8.0.4=pyhd8ed1ab_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.14=8_cp314
  - pytz=2025.2=pyhd8ed1ab_0
  - readline=8.2=h1d1bf99_2
  - requests=2.32.5=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py314hcc665ce_0
  - scipy=1.16.2=py314h624bdf2_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - text-unidecode=1.3=pyhd8ed1ab_2
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - zstandard=0.25.0=py314h163e31d_0
  - zstd=1.5.7=h6491c7d_2
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/kaggle
